spring:
  profiles:
    active: dev
  mvc:
    view:
        prefix: /WEB-INF/view/
        suffix: .jsp
  resources:
    static-locations: classpath:/WEB-INF/resources/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medcine?serverTimezone=UTC
    username: root
    password: woqu0310
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


